---
title: "How I Spend My Time"
subtitle: "SAT 231: Calendar Query"
author: "Kauila Tengan"
date: "Last updated \\today"
output: pdf_document
---

```{r setup, include = FALSE}
# load packages
library(tidyverse)
library(lubridate)
library(ical)

# set code chunk defaults
knitr::opts_chunk$set(tidy = F, # display code as typed
                      size = "small", # slightly smaller code font
                      message = FALSE,
                      warning = FALSE,
                      comment = "\t") 

# set black & white default plot theme 
# theme_set(theme_classic()) # uncomment this line if desired

# improve digit and NA display 
options(scipen = 1, knitr.kable.NA = '')
```

<!--
Please remove my comments from the code chunks and customize the code chunks on your own, including chunk labels and options and code documentation.

You can leave my markdown comments for guidance in writing your report.

Please rename the headings. 
You may add subheadings as desired to break up the report. 
-->

# YOUR REPORT HEADING <!-- (e.g., How do I spend my time?) -->

<!--
The code below is provided as a starting point for importing an `ics` file into R as a dataframe, doing some initial wrangling, and adding up the time spent on each activity. You are not required to use this code, so delete or modify it as you see fit. 

If you are using the code, be sure to update the capitalized parts with the relevant path to where your `ics` file is located, and set `eval = TRUE`.

As a reminder here's the link for exporting a Google calendar to ics (if on a Mac, you can hold cmd + click to open the page):
https://support.google.com/calendar/answer/37111?hl=en&ref_topic=10509946
-->
```{r, eval = FALSE}
# Data import and preliminary wrangling
calendar_data <- "ktdata3.ics" %>% 
  # Use ical package to import into R
  ical_parse_df() %>% 
  # Convert to "tibble" data frame format
  as_tibble() %>% 
  mutate(
    # Use lubridate package to wrangle dates and times
    start_datetime = with_tz(start, tzone = "America/New_York"),
    end_datetime = with_tz(end, tzone = "America/New_York"),
    duration_min = difftime(end_datetime, start_datetime, units = "mins"),
    # duration_min = end_datetime - start_datetime,
    date = floor_date(start_datetime, unit = "day"),
    # Convert calendar entry to all lowercase and rename
    activity = tolower(summary),
    overall = fct_collapse(factor(summary), #new overall variables for work/class
                           class = c("ASLC_class", "ASLC_study",
                                     "ENST_class", "ENST_OH", "ENST_study", 
                                     "NS_class", "NS_study", "STAT_class",
                                     "STAT_OH", "STAT_SDS", "STAT_study"),
                           work = c("work_divtern", "work_meeting", "work_NISA")
                           ),
    time = as.numeric(duration_min)) #making duration into a numeric
  
  #data wrangling for visualization 1
  class_data <- calendar_data %>% 
     #filter our overall variable by class only
    filter(overall == "class") %>% 
    #separating class and activity
    separate(summary, c("class", "activity"), "_", remove = FALSE) %>% 
    group_by(class, activity) %>% 
    summarize(overall_time = sum(time))
   

# Compute total duration of time for each day & activity
activities <- calendar_data %>% 
  group_by(date, overall) %>%
  summarize(duration_min = sum(duration_min))


```

<!--
Describe your question(s) here.  Briefly describe your data collection process, including how you defined variables of interest.
-->




<!--
Describe what information is conveyed through data visualization #1 (that you'll create below) here.
-->




```{r}
# Code for data visualization #1
# Be sure to provide meaningful title and axes labels 

ggplot(data = class_data, aes(fill = activity, y = overall_time, x = class)) +
  geom_bar(position = "stack", stat = "identity") +
  labs(title = "Time Devoted to Each Class",
       x = "Classes",
       y = "Total Time (min)") #+
  # scale_fill_brewer(palette = )
```

<!--
Describe what information is conveyed through data visualization #2 (that you'll create below) here.
-->



```{r}
# Code for data visualization #2
# Be sure to provide meaningful title and axes labels 
ggplot(calendar_data, aes(x = date, y = time,
                          color = overall)) + 
  geom_line() +
  labs(title = "Time Series Graph Over 2 Weeks",
       subtitle = "Amount of Time Devote to Each Task Each Day",
       y = "Total Time (Minutes)",
       x = "Date (YYYY-MM-DD)",
       color = "Overall", lty = "Overall") +
  #Change date breaks 
  scale_x_datetime(date_breaks = "1 days") +
  #increase y labels (add 10 breaks)
  scale_y_continuous(breaks = scales::pretty_breaks(n = 10)) + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1, size = rel(1)))
         
       
```

<!--
Describe what information is conveyed through the table (that you'll create below) here.

For nicer tables, check out:

* the kable function in the knitr package + the kableExtra package  
  https://bookdown.org/yihui/rmarkdown-cookbook/kable.html 
  https://bookdown.org/yihui/rmarkdown-cookbook/kableextra.html

or 

* the xtable package
  https://cran.r-project.org/web/packages/xtable/vignettes/xtableGallery.pdf
-->



```{r, results = 'asis'}
# Code for table
```

<!--
To conclude, briefly summarize what you found in response to the questions posed here.
-->


\newpage
# YOUR REFLECTION HEADING <!-- e.g., Reflection -->

<!--
Write your one-page reflection here in paragraph form.  In particular, address:

* What difficulties in the data collection and analysis process did you encounter?  Identify two of your main hurdles in gathering accurate data.

* What implications does that have for future data collection and/or analysis projects? 

* How much data do you think you'd need to collect in order to answer your question(s) of interest? Would it be hard to collect that data? Why or why not?

* As someone who provides data, what expectations do you have when you give your data (e.g. to Facebook, Google, MapMyRun, etc.)?  

* As someone who analyzes others' data, what ethical responsibilities do you have?
-->


